### ISSUE TITLE
Problem with xml processing when making an order on php 7.2

### ISSUE THREAD

**Issue by mdorrell** [Bandwidth/php-bandwidth-iris#28]
I found a problem using the order method. I am on php 7.2. In the file "core/Client.php" there is a method xml2array that doesn't work. It returns an empty object. I have written a little test script that shows it not working for the xml I have, and a version that does seem to work.
[bandwidthTest.zip](https://github.com/Bandwidth/php-bandwidth-iris/files/2728832/bandwidthTest.zip)

**Comment by ooglek** [comment]
I believe something changed between PHP 7.0 and 7.2 and 7.3 as I checked out master and the latest release of the code and ran PHPUnit tests:

```
FAILURES!
Tests: 111, Assertions: 169, Errors: 2, Failures: 85.
```

I'm going to dig into it myself as we need this working on PHP 7.3. Probably has to do with some SimpleXML Changes that PHP made in the last few releases. I'll report back when I have something working.

**Comment by ooglek** [comment]
Looks like xml2array() in `core/Client.php` is broken. I've replaced it but there are still tests failing. Digging into see why.

I replaced `xml2array()` with this temporarily

```
        $array = json_decode(json_encode((array)$xml), true);
        return $array;
```

which is similar to the xml2object() method.

**Comment by jmulford-bandwidth** [comment]
Hey everyone,

Thanks for helping out with this. I've actually been looking at this recently. I made a change that had all the unit tests working except for 2 of them, however it does work as expected with real requests against our API so it could just be that those unit tests are bad.

The change I made was changing

```
if (!empty($e))
```

to

```
if ($element->count() > 0)
```

in `xml2array()`.

Feel free to look at https://github.com/Bandwidth/php-bandwidth-iris/compare/DX-429 if you want to see the file changes. I'm hoping to have this pushed out this week

**Comment by ooglek** [comment]
With that one change it indeed reduces the errors and failures in PHP 7.3:

```
FAILURES!
Tests: 111, Assertions: 69, Errors: 71, Failures: 23.
```

Most are related to GET vs POST/PUT/DELETE or comparing Guzzle URLs.

**Comment by ooglek** [comment]
You also need to change this line:

```
                if (!$this->isAssoc($res) && is_array($res) && count($res) == 1) {
```

to 

```
                if (is_array($res) && !$this->isAssoc($res) && is_array($res) && count($res) == 1) {
```

With your change above @jmulford-bandwidth and this change we get down to picky details:

```
There were 2 failures:

1) DisconnectsTest::testDisconnectsGet
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'{"CountOfTNs":"1","userId":"smckinnon","lastModifiedDate":"2014-01-10T17-34-15Z","OrderId":"6d7da966-e071-4741-b31c-1d8932f4b8da","OrderType":"disconnect","OrderDate":"2014-01-10T17-34-15.797Z","OrderStatus":"COMPLETE","TelephoneNumberDetails":[]}'
+'{"CountOfTNs":"1","userId":"smckinnon","lastModifiedDate":"2014-01-10T17-34-15Z","OrderId":"6d7da966-e071-4741-b31c-1d8932f4b8da","OrderType":"disconnect","OrderDate":"2014-01-10T17-34-15.797Z","OrderStatus":"COMPLETE"}'

/usr/home/beckman/tmp/php-bandwidth-iris/tests/DisconnectsTest.php:54

2) DisconnectsTest::testDisconnectGet
Failed asserting that GuzzleHttp\Psr7\Uri Object &0000000048c05917000000002b6ea442 (
    'scheme' => 'https'
    'userInfo' => ''
    'host' => 'api.test.inetwork.com'
    'port' => null
    'path' => '/v1.0/accounts/9500249/disconnects'
    'query' => 'page=1&size=30'
    'fragment' => ''
) matches expected 'https://api.test.inetwork.com/v1.0/accounts/9500249/disconnects/b902dee1-0585-4258-becd-5c7e51ccf5e1?tndetail=true'.

/usr/home/beckman/tmp/php-bandwidth-iris/tests/DisconnectsTest.php:71

FAILURES!
Tests: 111, Assertions: 327, Failures: 2.
```

**Comment by jmulford-bandwidth** [comment]
@ooglek That's the same test fail I was getting that I'm not 100% sure accurately reflects an issue with the code. I'll add in your other change for php 7.3.5 compatibility (I'm assuming that last change is needed for compatibility with 7.3.5. I'm on 7.3.3 and didn't need that change)

**Comment by jmulford-bandwidth** [comment]
@ooglek I wasn't able to replicate any issues with 7.3.5. I got the same functionality with just replacing

```
            if (!empty($e))
```

with

```
            if ($element->count() > 0)
```

https://github.com/Bandwidth/php-bandwidth-iris/compare/DX-429

**Comment by jmulford-bandwidth** [comment]
Also I did a manual test and (at least with my account) I was getting the same result with the old SDK and these updates. I'm starting to think the unit tests that are failing are just incorrect

**Comment by ajrice6713** [comment]
Closing this issue as we are planning on moving to a different client altogether and are focusing the team efforts there. 

Feel free to open a PR with the suggested change and we would be happy to review and test - but it looks like @jmulford-bw was able to add the 7.3.5 capability (not sure which commit that is)
