### ISSUE TITLE
Missing "Zip" field of the model "Address"

### ISSUE THREAD

**Issue by Lardpower** [Bandwidth/php-bandwidth-iris#35]
A required field `Zip` is missing in model `Address` declared in the file `/vendor/bandwidth/iris/src/AddressModel.php`. This field is mandatory, because it's impossible to create a new Site (sub-account) with associated address that doesn't have valid zip code. In such case you'll receive the following error:

```
Uncaught Iris\ResponseException: Zip is required in /vendor/bandwidth/iris/core/Client.php:376 

Stack trace: 

#0 /vendor/bandwidth/iris/core/Client.php(284): Iris\Client->parseExceptionResponse(Object(GuzzleHttp\Exception\ClientException)) 
#1 /vendor/bandwidth/iris/core/Client.php(177): Iris\Client->request('post', 'accounts/MY_ACCOUNT_ID...', Array)
#2 /vendor/bandwidth/iris/src/RestEntry.php(65): Iris\Client->post('accounts/MY_ACCOUNT_ID...', 'Site', Array)
#3 /vendor/bandwidth/iris/src/Sites.php(95): Iris\RestEntry->post('accounts/MY_ACCOUNT_ID...', 'Site', Array) 
#4 /vendor/bandwidth/iris/src/Sites.php(51): Iris\Site->save()
```

And it's impossible to set a zip code for the site's associated address because such field isn't defined in the `\Iris\Address` model.

**Comment by jmulford-bandwidth** [comment]
Hi @Lardpower,

Thanks for pointing this out! If you've worked on a fix for this feel free to add a PR. Otherwise we'll be taking a lot at it on our team.

Thank you,

Jacob

**Comment by jmulford-bandwidth** [comment]
Hey @Lardpower,

We were able to come up with a fix. I'll open up a PR and if you want to take a look at it and confirm the changes feel free to do so. Thanks again!

**Comment by jmulford-bandwidth** [comment]
Fixed with most recent PR

**Comment by Lardpower** [comment]
@jmulford-bandwidth , thank you. Next time I'll come up with the PR.
