### ISSUE TITLE
account->reports()->instances() Broken, Incomplete

### ISSUE THREAD

**Issue by ooglek** [Bandwidth/php-bandwidth-iris#43]
I'm trying to use the Reports interface but it looks like it was started but never completed.

I'm trying to:

1. Get the Report Template for id 37 (don't think there are parameters but going for completeness)
2. POST to account->reports()->instances() to create a report
3. Loop on GET account->reports->instance(id) to see if it is done
4. Download the Report file.

The `ReportInstance` class is incomplete and **misspelled** as `ReportInctace` on line 101 of `ReportsModel.php`, and while GET instances() seems to be implemented, POST is not.

https://github.com/Bandwidth/php-bandwidth-iris/blob/1a6182e94052f1ac675b46fb943a10e83c076ca0/src/ReportsModel.php#L99-L103

_class ReportInstance_

https://github.com/Bandwidth/php-bandwidth-iris/blob/1a6182e94052f1ac675b46fb943a10e83c076ca0/src/ReportsModel.php#L113-L118

Once completed the main docs should be updated too.

**Comment by ooglek** [comment]
Here's a start on the model:

```
  final class InstanceParameters {
      use BaseModel;

      protected $fields = array(
          "Parameter" => array("type" => "\Iris\InstanceParameter")
      );
      public function __construct($data) {
          $this->set_data($data);
      }
  }

  final class InstanceParameter {
      use BaseModel;

      protected $fields = array(
          "Name" => array("type" => "string"),
          "Value" => array("type" => "string"),
      );
      public function __construct($data) {
          $this->set_data($data);
      }
  }

  final class ReportInstance extends RestEntry{
      use BaseModel;

!2    protected $fields = array(
          "Id" => array("type" => "string"),
          "ReportId" => array("type" => "string"),
          "ReportName" => array("type" => "string"),
          "OutputFormat" => array("type" => "string"),
          "RequestedByUserName" => array("type" => "string"),
          "RequestedAt" => array("type" => "string"),
          "Parameters" => array("type" => "\Iris\InstanceParameters"),
          "Status" => array("type" => "string"),
          "ExpiresAt" => array("type" => "string"),
      );
```

**Comment by jmulford-bandwidth** [comment]
Hey @ooglek we'll be looking into this this week! If you have any work you've done feel free to submit a PR and we can look at it. Thanks!

**Comment by ooglek** [comment]
The work I started is pasted above. I don't know what your coding and naming standards are, so I did not create all the InstanceParameter stuff any further than the model. I also didn't break it out into its own file.

I ended up working around it by making API calls directly. But if you get this done, I'll happily test it if you want to throw it on a branch.

**Comment by ooglek** [comment]
Unrelated but while I have your attention (I'll test your branch shortly)

In `core/Client.php` there is an opportunity to return the previous exception which caused the ResponseException with the raised new exception. This is wildly useful when trying to get the response message from bandwidth! We were having issues where Ports were being submitted, rejected, but the response data was not programmatically accessible from the ResponseException.

We made this change locally to allow us to access the error in full from the Guzzle response.

```
Index: include/common/port_functions.inc
===================================================================
--- include/common/port_functions.inc   (revision 5332)
+++ include/common/port_functions.inc   (revision 5333)
@@ -718,6 +718,12 @@
             $eclass = get_class($e);
             warning("portid:{$port['portid']} API threw unhandled {$eclass} exception " . $output);
             $errorMsg = "Unexpected error occurred";
+            try {
+                $doc = @simplexml_load_string($e->getPrevious()->getResponse()->getBody(true)->getContents());
+                warning("portid:{$port['portid']} xmltostring:" . strval($doc));
+            } catch (Exception $e2) {
+                warning("portid:{$port['portid']} xmltostring failed: " . $e->getMessage());
+            }
         }
         return 0;
     }
Index: include/vendor/bandwidth/iris/core/Client.php
===================================================================
--- include/vendor/bandwidth/iris/core/Client.php       (revision 5332)
+++ include/vendor/bandwidth/iris/core/Client.php       (revision 5333)
@@ -375,7 +375,8 @@
         {
             throw new ResponseException(
                 (string) $doc->ResponseStatus->Description,
-                (int) $doc->ResponseStatus->ErrorCode
+                (int) $doc->ResponseStatus->ErrorCode,
+                $e
             );
         }

@@ -386,10 +387,15 @@
         {
             throw new ResponseException(
                 (string) $doc->Error->Description,
-                (int) $doc->Error->Code
+                (int) $doc->Error->Code,
+                $e,
             );
         }

-        throw new ResponseException($e->getMessage(), $e->getResponse()->getStatusCode());
+        throw new ResponseException(
+            $e->getMessage(),
+            $e->getResponse()->getStatusCode(),
+            $e
+        );
     }
 }
```

**Comment by ooglek** [comment]
If I use my own account in production, I get an array with a single "Report" back, and it doesn't have an accessible property `Id` despite it being of class Iris\Report.

Same in development.

I'd assume reports()->getList() would return a more-full list of reports. It does not seem to.

I'll re-test when you have more code.

Also, `array()` should be lowercase for both PHP5 and 7.

**Comment by jmulford-bandwidth** [comment]
Hey I had a small bug with looping the response which is why you were only getting 1 report and that it didn't have the properties. That should be fixed now (fixed the same issue with looping on instances as well)

**Comment by jmulford-bandwidth** [comment]
> Unrelated but while I have your attention (I'll test your branch shortly)
> 
> In `core/Client.php` there is an opportunity to return the previous exception which caused the ResponseException with the raised new exception. This is wildly useful when trying to get the response message from bandwidth! We were having issues where Ports were being submitted, rejected, but the response data was not programmatically accessible from the ResponseException.
> 
> We made this change locally to allow us to access the error in full from the Guzzle response. The base PHP Exception provides an `$e->getPrevious()` method that if populated references the previous exception that caused the current exception.
> 
> https://www.php.net/manual/en/class.exception.php
> 
> ```
> Index: include/common/port_functions.inc
> ===================================================================
> --- include/common/port_functions.inc   (revision 5332)
> +++ include/common/port_functions.inc   (revision 5333)
> @@ -718,6 +718,12 @@
>              $eclass = get_class($e);
>              warning("portid:{$port['portid']} API threw unhandled {$eclass} exception " . $output);
>              $errorMsg = "Unexpected error occurred";
> +            try {
> +                $doc = @simplexml_load_string($e->getPrevious()->getResponse()->getBody(true)->getContents());
> +                debug("portid:{$port['portid']} xmltostring:" . strval($doc));
> +            } catch (Exception $e2) {
> +                warning("portid:{$port['portid']} xmltostring failed: " . $e2->getMessage());
> +            }
>          }
>          return 0;
>      }
> Index: include/vendor/bandwidth/iris/core/Client.php
> ===================================================================
> --- include/vendor/bandwidth/iris/core/Client.php       (revision 5332)
> +++ include/vendor/bandwidth/iris/core/Client.php       (revision 5333)
> @@ -375,7 +375,8 @@
>          {
>              throw new ResponseException(
>                  (string) $doc->ResponseStatus->Description,
> -                (int) $doc->ResponseStatus->ErrorCode
> +                (int) $doc->ResponseStatus->ErrorCode,
> +                $e
>              );
>          }
> 
> @@ -386,10 +387,15 @@
>          {
>              throw new ResponseException(
>                  (string) $doc->Error->Description,
> -                (int) $doc->Error->Code
> +                (int) $doc->Error->Code,
> +                $e,
>              );
>          }
> 
> -        throw new ResponseException($e->getMessage(), $e->getResponse()->getStatusCode());
> +        throw new ResponseException(
> +            $e->getMessage(),
> +            $e->getResponse()->getStatusCode(),
> +            $e
> +        );
>      }
>  }
> ```

I'll talk to the team about adding this! Definitely should be considered. Thank you!

**Comment by ooglek** [comment]
Any chance either of these have been addressed or considered? I'd love to see the changes.

**Comment by ajrice6713** [comment]
It looks like the original issue was resolved by @jmulford-bw so im going to go ahead and consider this stale and close it. 

As for the added original exception functionality - if that is still desired @ooglek would you mind opening a separate issue and we can triage that? 

Apologies for the delay - @jmulford-bw is no longer with the team and this wasn't passed off to anyone
