### ISSUE TITLE
Error when only 1 result in availableNumbers

### ISSUE THREAD

**Issue by piwel** [Bandwidth/php-bandwidth-iris#46]
Hi,

When you search for a specific number, resulting in one single result, the service returns ```{"count":0,"result":"error"}```
While BandWidth API correctly returns it.

Any clue how to fix this?

Thanks by advance.

**Comment by ajrice6713** [comment]
Hey @piwel 

Aplogies for the long overdue delay in response - this repository went stale for a while but we are looking to clean up any issues. 

I was not able to replicate this in my testing - its possible this was fixed in a version between when you opened the issue and now

```php
<?php

require "vendor/autoload.php";

$accountId = getenv("BW_ACCOUNT_ID");

$client = new \Iris\Client(getenv("BW_USERNAME"), getenv("BW_PASSWORD"), ['url' => 'https://dashboard.bandwidth.com/api/']);
$account = new \Iris\Account($accountId, $client);

function listAvailableNumbers() {
    global $account;
    $availableNumbers = $account->availableNumbers(["localVanity" => "9193716"]);
    echo json_encode($availableNumbers);
}

listAvailableNumbers();
```
