### ISSUE TITLE
Composer "Ambiguous class resolution" warning

### ISSUE THREAD

**Issue by tm1000** [Bandwidth/php-bandwidth-iris#56]
`Warning: Ambiguous class resolution, "Iris\OrderHistory" was found in both "/var/www/app/vendor/bandwidth/iris/src/simpleModels/History.php" and "/var/www/app/vendor/bandwidth/iris/src/simpleModels/OrderHistory.php", the first will be used.`

**Comment by jmulford-bw** [comment]
This will be fixed in our next release

**Comment by tm1000** [comment]
FYI this looks resolved @jmulford-bw.. closing :)

Thank you!
