### ISSUE TITLE
Uploading Bills for Verification

### ISSUE THREAD

**Issue by imovertheinternet** [Bandwidth/php-bandwidth-iris#59]
Hello,
During the portin process I have a question.
The `$account->portins()->create` method creates a LNPorder. After the LNP is created you can upload the LOA via `$portin->loas_send("./1.txt")`.  Is there any way to upload a bill (Image)? Ive heard of BW requiring bills as proof for address verification EG: Copy of Bill (COB).

https://support.bandwidth.com/hc/en-us/articles/204138426-Bandwidth-Porting-Guide#h_dba55caf-4f4e-447b-a52d-6b7de83a9fa9

**Comment by ajrice6713** [comment]
Hey @imovertheinternet - apologies for the incredibly long delay in getting back to you - this repo went stale for a little while and we are working on improving our open source presence (as well as our SDKs) 

You can use the `loas_send()` method to upload an image file - it doesnt need to be a .txt. A PDF is preferred if possible.
