### ISSUE TITLE
Invalid DocBlock @param 'type' in DisconnectsModel.php:create()

### ISSUE THREAD

**Issue by dmimms** [Bandwidth/php-bandwidth-iris#64]
The DocBlock for the create method in DisconnectsModel.php specifies that parameter $data should be of **type** instead of **array**, and that creates an error during code inspection.

**Comment by jmulford-bw** [comment]
Thanks @dmimms. v2.5.2 should have this fixed. Let me know if you have any more issues regarding this

**Comment by dmimms** [comment]
Thanks for the quick fix!
