### ISSUE TITLE
Duplicate Disconnect Attribute Definition

### ISSUE THREAD

**Issue by jklantz11** [Bandwidth/php-bandwidth-iris#76]
The OrderStatus seems to be getting defined twice here
https://github.com/Bandwidth/php-bandwidth-iris/blob/a10a1fd59534516ceb0b8ec50407c4bab26d1946/src/DisconnectsModel.php#L79

**Comment by ajrice6713** [comment]
@jklantz11 Thanks for pointing this out! We will investigate and get this cleared up shortly.
