### ISSUE TITLE
Order Model get parameter default

### ISSUE THREAD

**Issue by jklantz11** [Bandwidth/php-bandwidth-iris#77]
Is there a reason this parameter isn't defaulted to false like the other functions that do so?

https://github.com/Bandwidth/php-bandwidth-iris/blob/a10a1fd59534516ceb0b8ec50407c4bab26d1946/src/Order.php#L106

**Comment by ajrice6713** [comment]
Hey @jklantz11 ,

Not sure why this was originally defined with tndetail set to true, the API endpoint uses false as the default. 

I will discuss implications of changing this field with the team but see no reason not to follow the API.

**Comment by ajrice6713** [comment]
Hey @jklantz11 ,

It looks to me like `tnDetail` is being set to `false` [here](https://github.com/Bandwidth/php-bandwidth-iris/blob/7da2d33e10514fd26bb1ce467a249bb29298e8a7/src/Order.php#L43) in the `order` method of the `orders` class, which returns the `order()->get()` value and sets `tnDetail` to false by default.

It is not expected for `order()->get()` to be accessed directly - but instead through `orders()->order()` which sets `tnDetail` to false by default. 

Let me know if my findings are incorrect or if you have any other questions. I will close this out for the time being but feel free to reopen this if you feel it hasnt been resolved properly
