### ISSUE TITLE
TnOptionGroups don't support assigning A2pSettings (for 10DLC Campaigns)

### ISSUE THREAD

**Issue by brendangilmore** [Bandwidth/php-bandwidth-iris#81]
The TnOptionGroups model doesn't have support for A2pSettings which is required to assign campaigns to TNs for the upcoming carrier/industry requirements for 10DLC Campaigns. 
Documentation: https://dev.bandwidth.com/campaigns/csp/guides/bandwidth10dlcCampaignCspApiGuide.html#assign-a-campaign-to-a-tn

**Comment by ajrice6713** [comment]
Closing this issue as we are not planning to add support for those endpoints in this SDK

The team is currently working on generating new sdks across all languages that include all of the APIs (combining numbers, mes\saging, voice, etc) from the openapi specifications, where these endpoints would be supported 

Recommend workaround for the time being is to implement an HTTP client and use the API directly until the new clients are available.
