### ISSUE TITLE
How to make automatically "SMS", "MMS" and "VOICE" credit purchases from our provider ???

### ISSUE THREAD

**Issue by chegmarco1989** [Bandwidth/php-bandwidth-iris#92]
Hello.
I'm working with a group of friends on an Online Marketing project. We develop the web platform with the PHP LARAVEL Framework. The thing is that we plan to set up a sort of Bot in Pure PHP (Laravel being a basic PHP framework, also accepts the writing of raw PHP code) which will make it possible **to automatically make "SMS", "MMS" and "VOICE" credit purchases from our provider.**

So, it's only an idea... So, _we would like to know if there is a possibility to pay to subscribe to "SMS", "MMS" and "VOICE" subscriptions automatically using this PHP package ???_

**Is it possible to create in PHP, an automatic trigger or automatic payment on the site of our supplier "bandwith.com" without each time doing it manually or human intervention ???**

If yes, how to do it please using this PHP package???
Please guide us through.

**Comment by ajrice6713** [comment]
Hey @chegmarco1989! 

Are you asking about signing up for an account to be able to use the voice/sms services? 

If so - unfortunately we don't have an automated sign up process. You will have to reach out to our sales department M-F 9-5(EST) to request an account with access to the APIs. 

This SDK only allows for managing the account and purchasing/managing phone number inventory. 

[Bandwidth](https://www.bandwidth.com/)

**Comment by chegmarco1989** [comment]
Thank you for your reply. But apparently you don't understand us. We don't ask about automatic account creation.

**In fact, assuming that we have already created our account on "_bandwidth.com_". To send SMS via "_bandwidth_", we will need to have packages or credits for sending "_SMS/MSS/Voice_", right ???**

_Well, we would like to automate from our PHP application the reloading of "**SMS/MSS/Voice**" sending packages (from our account) without having to move to manually reload our account on "**bandwidth**"._

Do you understand now ???

If so, **how can we recharge our "SMS/MSS/Voice" account on "**bandwidth.com**" automatically from our PHP web application so as not to run out of packages or sending credits ???**

Please reply to us.

**Comment by ajrice6713** [comment]
Hey @chegmarco1989,

We don't have a concept of pre-paying/reloading the account in our billing system. 

You would receive an invoice for your monthly usage - you may be able to set up automatic credit card payments - but there is no SDK functionality to pay bills/reload credits.

**Comment by chegmarco1989** [comment]
Ok... If we understand correctly, we pay at the end of each month like for cloud servers ??? 

That's it ???

**Comment by ajrice6713** [comment]
@chegmarco1989 Correct, you would receive a monthly invoice for your usage (messages sent, calls sent and received, tn's purchased/monthly carrying cost) 

I think inbound messages are free but I'm not sure - you'd have to talk to a sales representative to get all of the info on pricing and options on paying the monthly invoice though, I'm not super well-versed in that side of the business. 

You'll also want to check out our other [php-sdk](https://github.com/Bandwidth/php-sdk) - this package is only for managing your telephone numbers. The other SDK is for actually sending SMS/MMS/Voice

**Comment by chegmarco1989** [comment]
All right. Thanks.

**Comment by chegmarco1989** [comment]
Can you delete this post from here please as it is not of the "problem" type. Thanks.

**Comment by chegmarco1989** [comment]
PLEASE DELETE THIS POST FOR US PLEASE BECAUSE WE CANNOT DO IT OURSELVES.
